coverage:
  status:
    project:
      default:
        target: auto
        threshold: null
        base: auto

comment: off

ignore:
  - "**/*story.js"
  - "**/registerServiceWorker.js"
  - "features"
  - "scripts/*.js"
  - "src/queries/*.js"
  - "tests"
