dist: trusty

sudo: required

services:
  - docker

language: node_js

node_js:
  - "8"

cache:
  yarn: true

addons:
  chrome: stable

install:
 - yarn install --frozen-lockfile

before_script:
 - set -e

script:
  - yarn lint
  - yarn coverage  
  - yarn test:storybook
  - yarn test:e2e
  - yarn storybook-build


after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - docker build -t onsdigital/eq-author:$TAG --build-arg APPLICATION_VERSION=$(git rev-parse HEAD) -f Dockerfile .
  - echo "Pushing with tag [$TAG]"
  - docker push onsdigital/eq-author:$TAG
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION

env:
  global:
    - NODE_PATH=src/
    - secure: "VjPAigrcPT4oeUmefAmY4DbgKZU7eZPsTp9dJv3OusYzlq00bPdlPT0evxJ8CzoZ1MeI+yc910dZgR3RqzObN7fhZKwl9fLkxYCtTDByZb2uN56NpyIv7XBEN8MsaMYwSRWNNIn7W+/ymzLCFnkx5S/hOkZ0inbfWEom5YOysJF5aqIBj8EGpI17me3XvWCuPlF8TOm5DSURbXLOqJpxQ+mFn68ibWi4S6YbgBiuMtHQI682EHQB5hwjEeO+L5aR7xiP1fw0Romcopao+kH+NPmmvJ6OhpzIric5B4ZtekuOaqIOaKY2jRLfYWCN9LC2BLD/1jGA3U5IBX1R3+8Svd6AR42e1IlEr42Iu9VBaL8sA3YTTcBAX/kTCBdSMg14fvQjjHb1QUYNMLa+ewOhKU/FjC0qj5poUaOVfx2nEyK6xKe8BaKtFPXb+RqSDCTH1AjqQVDlidn12leNUF9HxA1UYwuT99rC5C9ixeinpfmqooGiq3MQBf3/zibkYbnbxNLWhTk1krfoJ9QFkEMc0zNvzqijOA7+irOiBc4nfsQbEvS/87v68HiICRnoM9ur9EOne6s0QuHHCY6M2BjCqnpM67zvBtLkWUr558Svrd2ZsFnWIQR82pFXabltZPQWkUy1Ton3mBz8c/vxcKZ4GpxlfTM5PQx/QQNyAkvT+FU="

deploy:
  local_dir: storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch:
      - master

branches:
    only:
        - master