dist: trusty

sudo: required

language: node_js

node_js:
  - "7"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

install:
 - yarn install

before_script:
 - yarn global add chimp
 - yarn global add serve
 - set -e

script:
  - yarn lint -- --max-warnings=0
  - yarn test
  - yarn coverage
  - ./scripts/run_smoketests_author.sh
  - ./scripts/run_smoketests_storybook.sh

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - docker build -t onsdigital/eq-author:$TAG -f Dockerfile .
  - echo "Pushing with tag [$TAG]"
  - docker push onsdigital/eq-author:$TAG
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
  - yarn storybook-build

env:
  global:
    - CXX=g++-4.8
    - NODE_PATH=src/
    - secure: "qblndTDPo9a012liS9C4dvXV8gbgyLc1aEsLoh/rM482/vuIEUDvRw/jyK5bzMqy6nHc9sRVpTsTsJpm5inPQW5oogod98LOdHJX3AzDTWSmvXt70UOEyCY/iT5FoC1Ypud/Rli+WcmmGoFEb2nDajCKQ8wf2LD/EIXdSXuDj5zViUugTRVbU8oAc9c7OV0EE82IzyioDjqZbAVhMCVMwwctgWO2uZUJUc65NlL4dmBGjB2iJDae3YDuENSZBVr0PdUmmeyWReRV34ZZ/2rJ5ZqKW/V9FhnUCR8vVAFJioxCyAm6GWAQ7KZhpvZLrBER36kOSWotc7ddaT204hYomk5DbZrB9h6DXtCXpkLHgGFU5bRVI9O5+M0Gn6FuDIcEQkZwwoB3Ttgcrczu7XpSsUei8rfZIN+wNVwsrNHXiC/yWD9vvedXzs3RhgJzOpqAPLFaQ79Ky1oD6UxanBFtyH9O0cFglUu0081MsjUPVCx3CiAe3NJYiGAxMg2xtFCo9Zf+SMI1LAt6+WeLbBNVPxIJZRq8a0jWhGNtz98XApF7GFFOv7b1gyVrrNi6YSkLp0m0Wz55cACTTUJRakuPZH14lq4E8pZYyU6meZFubrYg8GpZJox01Kq7DC9DNxS36LxNBe1MQ7K78VZAh1+HpicWUTZxfy3/s4WRSkz/pgg="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

deploy:
  local_dir: storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch:
      - master

branches:
    only:
        - master