language: node_js
node_js:
  - "7"

cache: yarn

script:
  - yarn lint -- --max-warnings=0
  - yarn test -- --coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8