// flow-typed signature: 0d86a5644adafcea05d67d88e8d933ab
// flow-typed version: <<STUB>>/chimp_v^0.49.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chimp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "chimp" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "chimp/bin/chimp" {
  declare module.exports: any;
}

declare module "chimp/chimp" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/bluebird" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/chokidar" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/colors" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/ddp" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/freeport" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/hapi" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/request" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/selenium-standalone" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/webdriverio" {
  declare module.exports: any;
}

declare module "chimp/dist/__mocks__/xolvio-sync-webdriverio" {
  declare module.exports: any;
}

declare module "chimp/dist/bin/chimp" {
  declare module.exports: any;
}

declare module "chimp/dist/bin/default" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/babel-register" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/boolean-helper" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/browserstack-manager" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/chimp-helper" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/chimp" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/chromedriver" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/ci" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/consoler" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/cucumberjs/cucumber-wrapper" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/cucumberjs/cucumber" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/cucumberjs/hooks" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/cucumberjs/world" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/ddp-watcher" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/ddp" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/environment-variable-parsers" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/jasmine/jasmine-fiberized-api" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/jasmine/jasmine-helpers" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/jasmine/jasmine-wrapper" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/jasmine/jasmine" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/log" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/mocha/mocha-fiberized-ui" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/mocha/mocha-helper" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/mocha/mocha-wrapper-instance" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/mocha/mocha-wrapper" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/mocha/mocha" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/options-loader" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/phantom" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/process-helper" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/saucelabs-manager" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/screenshot-helper" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/selenium" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/session-factory" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/session-manager" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/simian-reporter" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/testingbot-manager" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/utils/escape-reg-exp" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/utils/fiberize" {
  declare module.exports: any;
}

declare module "chimp/dist/lib/versions" {
  declare module.exports: any;
}

declare module "chimp/features/step_definitions/es2015-steps" {
  declare module.exports: any;
}

declare module "chimp/features/step_definitions/webdriver-steps" {
  declare module.exports: any;
}

declare module "chimp/mocha-setup" {
  declare module.exports: any;
}

declare module "chimp/tests/cucumber/features/step_definitions/Given_global_pending_is_defined" {
  declare module.exports: any;
}

declare module "chimp/tests/jasmine/jasmine-spec" {
  declare module.exports: any;
}

declare module "chimp/tests/mocha/mocha-spec" {
  declare module.exports: any;
}

declare module "chimp/wallaby-mocha" {
  declare module.exports: any;
}

declare module "chimp/wallaby" {
  declare module.exports: any;
}

// Filename aliases
declare module "chimp/bin/chimp.js" {
  declare module.exports: $Exports<"chimp/bin/chimp">;
}
declare module "chimp/chimp.js" {
  declare module.exports: $Exports<"chimp/chimp">;
}
declare module "chimp/dist/__mocks__/bluebird.js" {
  declare module.exports: $Exports<"chimp/dist/__mocks__/bluebird">;
}
declare module "chimp/dist/__mocks__/chokidar.js" {
  declare module.exports: $Exports<"chimp/dist/__mocks__/chokidar">;
}
declare module "chimp/dist/__mocks__/colors.js" {
  declare module.exports: $Exports<"chimp/dist/__mocks__/colors">;
}
declare module "chimp/dist/__mocks__/ddp.js" {
  declare module.exports: $Exports<"chimp/dist/__mocks__/ddp">;
}
declare module "chimp/dist/__mocks__/freeport.js" {
  declare module.exports: $Exports<"chimp/dist/__mocks__/freeport">;
}
declare module "chimp/dist/__mocks__/hapi.js" {
  declare module.exports: $Exports<"chimp/dist/__mocks__/hapi">;
}
declare module "chimp/dist/__mocks__/request.js" {
  declare module.exports: $Exports<"chimp/dist/__mocks__/request">;
}
declare module "chimp/dist/__mocks__/selenium-standalone.js" {
  declare module.exports: $Exports<"chimp/dist/__mocks__/selenium-standalone">;
}
declare module "chimp/dist/__mocks__/webdriverio.js" {
  declare module.exports: $Exports<"chimp/dist/__mocks__/webdriverio">;
}
declare module "chimp/dist/__mocks__/xolvio-sync-webdriverio.js" {
  declare module.exports: $Exports<
    "chimp/dist/__mocks__/xolvio-sync-webdriverio"
  >;
}
declare module "chimp/dist/bin/chimp.js" {
  declare module.exports: $Exports<"chimp/dist/bin/chimp">;
}
declare module "chimp/dist/bin/default.js" {
  declare module.exports: $Exports<"chimp/dist/bin/default">;
}
declare module "chimp/dist/lib/babel-register.js" {
  declare module.exports: $Exports<"chimp/dist/lib/babel-register">;
}
declare module "chimp/dist/lib/boolean-helper.js" {
  declare module.exports: $Exports<"chimp/dist/lib/boolean-helper">;
}
declare module "chimp/dist/lib/browserstack-manager.js" {
  declare module.exports: $Exports<"chimp/dist/lib/browserstack-manager">;
}
declare module "chimp/dist/lib/chimp-helper.js" {
  declare module.exports: $Exports<"chimp/dist/lib/chimp-helper">;
}
declare module "chimp/dist/lib/chimp.js" {
  declare module.exports: $Exports<"chimp/dist/lib/chimp">;
}
declare module "chimp/dist/lib/chromedriver.js" {
  declare module.exports: $Exports<"chimp/dist/lib/chromedriver">;
}
declare module "chimp/dist/lib/ci.js" {
  declare module.exports: $Exports<"chimp/dist/lib/ci">;
}
declare module "chimp/dist/lib/consoler.js" {
  declare module.exports: $Exports<"chimp/dist/lib/consoler">;
}
declare module "chimp/dist/lib/cucumberjs/cucumber-wrapper.js" {
  declare module.exports: $Exports<
    "chimp/dist/lib/cucumberjs/cucumber-wrapper"
  >;
}
declare module "chimp/dist/lib/cucumberjs/cucumber.js" {
  declare module.exports: $Exports<"chimp/dist/lib/cucumberjs/cucumber">;
}
declare module "chimp/dist/lib/cucumberjs/hooks.js" {
  declare module.exports: $Exports<"chimp/dist/lib/cucumberjs/hooks">;
}
declare module "chimp/dist/lib/cucumberjs/world.js" {
  declare module.exports: $Exports<"chimp/dist/lib/cucumberjs/world">;
}
declare module "chimp/dist/lib/ddp-watcher.js" {
  declare module.exports: $Exports<"chimp/dist/lib/ddp-watcher">;
}
declare module "chimp/dist/lib/ddp.js" {
  declare module.exports: $Exports<"chimp/dist/lib/ddp">;
}
declare module "chimp/dist/lib/environment-variable-parsers.js" {
  declare module.exports: $Exports<
    "chimp/dist/lib/environment-variable-parsers"
  >;
}
declare module "chimp/dist/lib/jasmine/jasmine-fiberized-api.js" {
  declare module.exports: $Exports<
    "chimp/dist/lib/jasmine/jasmine-fiberized-api"
  >;
}
declare module "chimp/dist/lib/jasmine/jasmine-helpers.js" {
  declare module.exports: $Exports<"chimp/dist/lib/jasmine/jasmine-helpers">;
}
declare module "chimp/dist/lib/jasmine/jasmine-wrapper.js" {
  declare module.exports: $Exports<"chimp/dist/lib/jasmine/jasmine-wrapper">;
}
declare module "chimp/dist/lib/jasmine/jasmine.js" {
  declare module.exports: $Exports<"chimp/dist/lib/jasmine/jasmine">;
}
declare module "chimp/dist/lib/log.js" {
  declare module.exports: $Exports<"chimp/dist/lib/log">;
}
declare module "chimp/dist/lib/mocha/mocha-fiberized-ui.js" {
  declare module.exports: $Exports<"chimp/dist/lib/mocha/mocha-fiberized-ui">;
}
declare module "chimp/dist/lib/mocha/mocha-helper.js" {
  declare module.exports: $Exports<"chimp/dist/lib/mocha/mocha-helper">;
}
declare module "chimp/dist/lib/mocha/mocha-wrapper-instance.js" {
  declare module.exports: $Exports<
    "chimp/dist/lib/mocha/mocha-wrapper-instance"
  >;
}
declare module "chimp/dist/lib/mocha/mocha-wrapper.js" {
  declare module.exports: $Exports<"chimp/dist/lib/mocha/mocha-wrapper">;
}
declare module "chimp/dist/lib/mocha/mocha.js" {
  declare module.exports: $Exports<"chimp/dist/lib/mocha/mocha">;
}
declare module "chimp/dist/lib/options-loader.js" {
  declare module.exports: $Exports<"chimp/dist/lib/options-loader">;
}
declare module "chimp/dist/lib/phantom.js" {
  declare module.exports: $Exports<"chimp/dist/lib/phantom">;
}
declare module "chimp/dist/lib/process-helper.js" {
  declare module.exports: $Exports<"chimp/dist/lib/process-helper">;
}
declare module "chimp/dist/lib/saucelabs-manager.js" {
  declare module.exports: $Exports<"chimp/dist/lib/saucelabs-manager">;
}
declare module "chimp/dist/lib/screenshot-helper.js" {
  declare module.exports: $Exports<"chimp/dist/lib/screenshot-helper">;
}
declare module "chimp/dist/lib/selenium.js" {
  declare module.exports: $Exports<"chimp/dist/lib/selenium">;
}
declare module "chimp/dist/lib/session-factory.js" {
  declare module.exports: $Exports<"chimp/dist/lib/session-factory">;
}
declare module "chimp/dist/lib/session-manager.js" {
  declare module.exports: $Exports<"chimp/dist/lib/session-manager">;
}
declare module "chimp/dist/lib/simian-reporter.js" {
  declare module.exports: $Exports<"chimp/dist/lib/simian-reporter">;
}
declare module "chimp/dist/lib/testingbot-manager.js" {
  declare module.exports: $Exports<"chimp/dist/lib/testingbot-manager">;
}
declare module "chimp/dist/lib/utils/escape-reg-exp.js" {
  declare module.exports: $Exports<"chimp/dist/lib/utils/escape-reg-exp">;
}
declare module "chimp/dist/lib/utils/fiberize.js" {
  declare module.exports: $Exports<"chimp/dist/lib/utils/fiberize">;
}
declare module "chimp/dist/lib/versions.js" {
  declare module.exports: $Exports<"chimp/dist/lib/versions">;
}
declare module "chimp/features/step_definitions/es2015-steps.js" {
  declare module.exports: $Exports<
    "chimp/features/step_definitions/es2015-steps"
  >;
}
declare module "chimp/features/step_definitions/webdriver-steps.js" {
  declare module.exports: $Exports<
    "chimp/features/step_definitions/webdriver-steps"
  >;
}
declare module "chimp/index" {
  declare module.exports: $Exports<"chimp">;
}
declare module "chimp/index.js" {
  declare module.exports: $Exports<"chimp">;
}
declare module "chimp/mocha-setup.js" {
  declare module.exports: $Exports<"chimp/mocha-setup">;
}
declare module "chimp/tests/cucumber/features/step_definitions/Given_global_pending_is_defined.js" {
  declare module.exports: $Exports<
    "chimp/tests/cucumber/features/step_definitions/Given_global_pending_is_defined"
  >;
}
declare module "chimp/tests/jasmine/jasmine-spec.js" {
  declare module.exports: $Exports<"chimp/tests/jasmine/jasmine-spec">;
}
declare module "chimp/tests/mocha/mocha-spec.js" {
  declare module.exports: $Exports<"chimp/tests/mocha/mocha-spec">;
}
declare module "chimp/wallaby-mocha.js" {
  declare module.exports: $Exports<"chimp/wallaby-mocha">;
}
declare module "chimp/wallaby.js" {
  declare module.exports: $Exports<"chimp/wallaby">;
}
