// flow-typed signature: 3ace84834922c4cf2c1a1d6a8f5b6ed8
// flow-typed version: <<STUB>>/connect-history-api-fallback_v1.3.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-history-api-fallback'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "connect-history-api-fallback" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "connect-history-api-fallback/lib/index" {
  declare module.exports: any;
}

declare module "connect-history-api-fallback/test/index_test" {
  declare module.exports: any;
}

// Filename aliases
declare module "connect-history-api-fallback/lib/index.js" {
  declare module.exports: $Exports<"connect-history-api-fallback/lib/index">;
}
declare module "connect-history-api-fallback/test/index_test.js" {
  declare module.exports: $Exports<
    "connect-history-api-fallback/test/index_test"
  >;
}
