// flow-typed signature: 093e0e5461f3586b4827465589755c59
// flow-typed version: <<STUB>>/eq-author-graphql-schema_vhttps://github.com/ONSdigital/eq-author-graphql-schema.git/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eq-author-graphql-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "eq-author-graphql-schema" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "eq-author-graphql-schema/schema" {
  declare module.exports: any;
}

// Filename aliases
declare module "eq-author-graphql-schema/schema.js" {
  declare module.exports: $Exports<"eq-author-graphql-schema/schema">;
}
