// flow-typed signature: 4b7b1b72c77388f7d859f0da7b205ea6
// flow-typed version: <<STUB>>/eslint-config-eq-author_v^1.0.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-eq-author'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "eslint-config-eq-author" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "eslint-config-eq-author/react" {
  declare module.exports: any;
}

// Filename aliases
declare module "eslint-config-eq-author/index" {
  declare module.exports: $Exports<"eslint-config-eq-author">;
}
declare module "eslint-config-eq-author/index.js" {
  declare module.exports: $Exports<"eslint-config-eq-author">;
}
declare module "eslint-config-eq-author/react.js" {
  declare module.exports: $Exports<"eslint-config-eq-author/react">;
}
