// flow-typed signature: 843bfc02281ad4ab1ef21f1d497f28c5
// flow-typed version: <<STUB>>/node-glob_v^1.2.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "node-glob" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "node-glob/tests/FilesystemMock" {
  declare module.exports: any;
}

declare module "node-glob/tests/FinderTests" {
  declare module.exports: any;
}

// Filename aliases
declare module "node-glob/index" {
  declare module.exports: $Exports<"node-glob">;
}
declare module "node-glob/index.js" {
  declare module.exports: $Exports<"node-glob">;
}
declare module "node-glob/tests/FilesystemMock.js" {
  declare module.exports: $Exports<"node-glob/tests/FilesystemMock">;
}
declare module "node-glob/tests/FinderTests.js" {
  declare module.exports: $Exports<"node-glob/tests/FinderTests">;
}
