// flow-typed signature: 1e0ec216566b2b58c81cbc1eabac960a
// flow-typed version: <<STUB>>/react-textarea-autosize_v^5.0.7/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-textarea-autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-textarea-autosize" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-textarea-autosize/dist/react-textarea-autosize" {
  declare module.exports: any;
}

declare module "react-textarea-autosize/dist/react-textarea-autosize.min" {
  declare module.exports: any;
}

declare module "react-textarea-autosize/es/calculateNodeHeight" {
  declare module.exports: any;
}

declare module "react-textarea-autosize/es/index" {
  declare module.exports: any;
}

declare module "react-textarea-autosize/es/isBrowser" {
  declare module.exports: any;
}

declare module "react-textarea-autosize/es/uid" {
  declare module.exports: any;
}

declare module "react-textarea-autosize/lib/calculateNodeHeight" {
  declare module.exports: any;
}

declare module "react-textarea-autosize/lib/index" {
  declare module.exports: any;
}

declare module "react-textarea-autosize/lib/isBrowser" {
  declare module.exports: any;
}

declare module "react-textarea-autosize/lib/uid" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-textarea-autosize/dist/react-textarea-autosize.js" {
  declare module.exports: $Exports<
    "react-textarea-autosize/dist/react-textarea-autosize"
  >;
}
declare module "react-textarea-autosize/dist/react-textarea-autosize.min.js" {
  declare module.exports: $Exports<
    "react-textarea-autosize/dist/react-textarea-autosize.min"
  >;
}
declare module "react-textarea-autosize/es/calculateNodeHeight.js" {
  declare module.exports: $Exports<
    "react-textarea-autosize/es/calculateNodeHeight"
  >;
}
declare module "react-textarea-autosize/es/index.js" {
  declare module.exports: $Exports<"react-textarea-autosize/es/index">;
}
declare module "react-textarea-autosize/es/isBrowser.js" {
  declare module.exports: $Exports<"react-textarea-autosize/es/isBrowser">;
}
declare module "react-textarea-autosize/es/uid.js" {
  declare module.exports: $Exports<"react-textarea-autosize/es/uid">;
}
declare module "react-textarea-autosize/lib/calculateNodeHeight.js" {
  declare module.exports: $Exports<
    "react-textarea-autosize/lib/calculateNodeHeight"
  >;
}
declare module "react-textarea-autosize/lib/index.js" {
  declare module.exports: $Exports<"react-textarea-autosize/lib/index">;
}
declare module "react-textarea-autosize/lib/isBrowser.js" {
  declare module.exports: $Exports<"react-textarea-autosize/lib/isBrowser">;
}
declare module "react-textarea-autosize/lib/uid.js" {
  declare module.exports: $Exports<"react-textarea-autosize/lib/uid">;
}
