// flow-typed signature: c4b8f54265c0e443e114b4ebf408dd10
// flow-typed version: <<STUB>>/react-router-test-context_v^0.1.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-test-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-router-test-context" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "react-router-test-context/index" {
  declare module.exports: $Exports<"react-router-test-context">;
}
declare module "react-router-test-context/index.js" {
  declare module.exports: $Exports<"react-router-test-context">;
}
