// flow-typed signature: b40858f8d50cce505d557b526423c821
// flow-typed version: <<STUB>>/storybook-router_v^0.2.8/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "storybook-router" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "storybook-router/dist/StoryRouter" {
  declare module.exports: any;
}

// Filename aliases
declare module "storybook-router/dist/StoryRouter.js" {
  declare module.exports: $Exports<"storybook-router/dist/StoryRouter">;
}
