// flow-typed signature: ef5d15610d2205a773cb5c32467df072
// flow-typed version: <<STUB>>/svg-url-loader_v^2.0.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-url-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "svg-url-loader" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "svg-url-loader/test/input/css" {
  declare module.exports: any;
}

declare module "svg-url-loader/test/input/icon-with-declaration" {
  declare module.exports: any;
}

declare module "svg-url-loader/test/input/icon" {
  declare module.exports: any;
}

declare module "svg-url-loader/test/input/less" {
  declare module.exports: any;
}

declare module "svg-url-loader/test/input/scss" {
  declare module.exports: any;
}

declare module "svg-url-loader/test/loader.spec" {
  declare module.exports: any;
}

// Filename aliases
declare module "svg-url-loader/index" {
  declare module.exports: $Exports<"svg-url-loader">;
}
declare module "svg-url-loader/index.js" {
  declare module.exports: $Exports<"svg-url-loader">;
}
declare module "svg-url-loader/test/input/css.js" {
  declare module.exports: $Exports<"svg-url-loader/test/input/css">;
}
declare module "svg-url-loader/test/input/icon-with-declaration.js" {
  declare module.exports: $Exports<
    "svg-url-loader/test/input/icon-with-declaration"
  >;
}
declare module "svg-url-loader/test/input/icon.js" {
  declare module.exports: $Exports<"svg-url-loader/test/input/icon">;
}
declare module "svg-url-loader/test/input/less.js" {
  declare module.exports: $Exports<"svg-url-loader/test/input/less">;
}
declare module "svg-url-loader/test/input/scss.js" {
  declare module.exports: $Exports<"svg-url-loader/test/input/scss">;
}
declare module "svg-url-loader/test/loader.spec.js" {
  declare module.exports: $Exports<"svg-url-loader/test/loader.spec">;
}
