// flow-typed signature: b783bda11f4b7196caaaa47fbb05e5cb
// flow-typed version: <<STUB>>/uncontrollable_v^4.1.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uncontrollable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "uncontrollable" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "uncontrollable/batching" {
  declare module.exports: any;
}

declare module "uncontrollable/createUncontrollable" {
  declare module.exports: any;
}

declare module "uncontrollable/utils" {
  declare module.exports: any;
}

// Filename aliases
declare module "uncontrollable/batching.js" {
  declare module.exports: $Exports<"uncontrollable/batching">;
}
declare module "uncontrollable/createUncontrollable.js" {
  declare module.exports: $Exports<"uncontrollable/createUncontrollable">;
}
declare module "uncontrollable/index" {
  declare module.exports: $Exports<"uncontrollable">;
}
declare module "uncontrollable/index.js" {
  declare module.exports: $Exports<"uncontrollable">;
}
declare module "uncontrollable/utils.js" {
  declare module.exports: $Exports<"uncontrollable/utils">;
}
