version: "3"

services:
  eq-author-api:
    image: onsdigital/eq-author-api
    networks:
      - eq-author
    environment:
      DB_CONNECTION_URI: postgres://postgres:mysecretpassword@eq-author-db:5432/postgres
    depends_on:
      - eq-author-db
    ports:
      - 4000:4000
  eq-author-db:
    image: postgres:9.4-alpine
    networks:
      - eq-author
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - 5432

networks:
  eq-author:
    driver: bridge
